In [1]:
import pandas as pd

In [11]:
df = pd.read_csv("X_test_onehot.csv")

In [3]:
# df = df.rename(columns={'Unnamed: 0':'id'})

In [12]:
df.head()

,id,age_group_1,age_group_2,age_group_3,age_group_4,age_group_5,age_group_6,race_1,race_2,race_3,...,alcohol_consumption_cat_1,alcohol_consumption_cat_2,alcohol_consumption_cat_3,sex,physical_activity,smoking_status,high_blood_pressure,high_cholesterol,heart_disease,kidney_disease
0,398996,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1,1,0,0,0,0,0
1,216888,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1,0,1,1,1,1,0
2,278954,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1,0,0,1,0,0,0
3,138288,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0,1,0,1,0,0,0
4,336864,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,1,1,0,1,0,0,0

In [8]:
df = df.set_index('id')

In [9]:
df.head()

,age_group_1,age_group_2,age_group_3,age_group_4,age_group_5,age_group_6,race_1,race_2,race_3,race_4,...,alcohol_consumption_cat_1,alcohol_consumption_cat_2,alcohol_consumption_cat_3,sex,physical_activity,smoking_status,high_blood_pressure,high_cholesterol,heart_disease,kidney_disease
id,,,,,,,,,,,,,,,,,,,,,
398996,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1,1,0,0,0,0,0
216888,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1,0,1,1,1,1,0
278954,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1,0,0,1,0,0,0
138288,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0,1,0,1,0,0,0
336864,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,1,1,0,1,0,0,0

In [10]:
# df.to_csv('../data/X_test_onehot.csv')

In [13]:
df.columns

Index(['id', 'age_group_1', 'age_group_2', 'age_group_3', 'age_group_4',
       'age_group_5', 'age_group_6', 'race_1', 'race_2', 'race_3', 'race_4',
       'race_5', 'race_6', 'education_1', 'education_2', 'education_3',
       'education_4', 'bmi_category_1', 'bmi_category_2', 'bmi_category_3',
       'bmi_category_4', 'alcohol_consumption_cat_0',
       'alcohol_consumption_cat_1', 'alcohol_consumption_cat_2',
       'alcohol_consumption_cat_3', 'sex', 'physical_activity',
       'smoking_status', 'high_blood_pressure', 'high_cholesterol',
       'heart_disease', 'kidney_disease'],
      dtype='object')